# Generated by Django 3.2.4 on 2022-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('date_of_birth', models.DateField(default='')),
                ('phone', models.BigIntegerField()),
                ('grade', models.IntegerField()),
                ('email', models.EmailField(default='', max_length=30)),
            ],
        ),
    ]
